--GROUP_CATALOG
INSERT INTO GROUP_CATALOG VALUES('SP', 'SECTOR PRODUCTIVO', 't');
INSERT INTO GROUP_CATALOG VALUES('TD', 'TIPO DOCUMENTO', 't');
INSERT INTO GROUP_CATALOG VALUES('HT', 'HORARIO DE TRABAJO', 't');
INSERT INTO GROUP_CATALOG VALUES('TP', 'TIPO COMPAÑIA', 't');
INSERT INTO GROUP_CATALOG VALUES('TT', 'TIPO TELEFONO', 't');

--CATALOG
INSERT INTO CATALOG VALUES('BR','SP', 'BAJO RIESGO', 't');
INSERT INTO CATALOG VALUES('MR','SP', 'MEDIANO RIESGO', 't');
INSERT INTO CATALOG VALUES('AR','SP', 'ALTO RIESGO', 't');
INSERT INTO CATALOG VALUES('CI','TD', 'CEDULA', 'T');
INSERT INTO CATALOG VALUES('RUC','TD', 'RUC', 'T');
INSERT INTO CATALOG VALUES('J8','HT', 'JORNADA 8 HORAS', 't');
INSERT INTO CATALOG VALUES('JC','HT', 'JORNADA CONTINUA', 't');
INSERT INTO CATALOG VALUES('MICRO','TP', 'MICRO[1-9]', 'T');
INSERT INTO CATALOG VALUES('PEQ','TP', 'PEQUEÑA[10-49]', 'T');
INSERT INTO CATALOG VALUES('MED','TP', 'MEDIANA[50-199]', 'T');
INSERT INTO CATALOG VALUES('GRAN','TP', 'GRANDE[200 Y MAS]', 'T');
INSERT INTO CATALOG VALUES('CEL','TT', 'CELULAR', 'T');
INSERT INTO CATALOG VALUES('TEL','TT', 'TELEFONO', 'T');

-- Div geo pol

INSERT INTO GEOPOLITICAL_DIVISION VALUES(1,null, 'Ecuador', 't');
INSERT INTO GEOPOLITICAL_DIVISION VALUES(2,1, 'Pichincha', 't');
INSERT INTO GEOPOLITICAL_DIVISION VALUES(3,2, 'Quito', 't');
